// Code generated by MockGen. DO NOT EDIT.
// Source: grpc_operations_client_factory.go

// Package operations is a generated GoMock package.
package operations

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	operations "github.com/pivonroll/EventStore-Client-Go/protos/operations"
	grpc "google.golang.org/grpc"
)

// MockgrpcOperationsClientFactory is a mock of grpcOperationsClientFactory interface.
type MockgrpcOperationsClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockgrpcOperationsClientFactoryMockRecorder
}

// MockgrpcOperationsClientFactoryMockRecorder is the mock recorder for MockgrpcOperationsClientFactory.
type MockgrpcOperationsClientFactoryMockRecorder struct {
	mock *MockgrpcOperationsClientFactory
}

// NewMockgrpcOperationsClientFactory creates a new mock instance.
func NewMockgrpcOperationsClientFactory(ctrl *gomock.Controller) *MockgrpcOperationsClientFactory {
	mock := &MockgrpcOperationsClientFactory{ctrl: ctrl}
	mock.recorder = &MockgrpcOperationsClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgrpcOperationsClientFactory) EXPECT() *MockgrpcOperationsClientFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockgrpcOperationsClientFactory) Create(arg0 *grpc.ClientConn) operations.OperationsClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(operations.OperationsClient)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockgrpcOperationsClientFactoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockgrpcOperationsClientFactory)(nil).Create), arg0)
}
