// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streams.proto

package event_store_grpc_streams

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadReq_Options_ReadDirection int32

const (
	ReadReq_Options_Forwards  ReadReq_Options_ReadDirection = 0
	ReadReq_Options_Backwards ReadReq_Options_ReadDirection = 1
)

var ReadReq_Options_ReadDirection_name = map[int32]string{
	0: "Forwards",
	1: "Backwards",
}

var ReadReq_Options_ReadDirection_value = map[string]int32{
	"Forwards":  0,
	"Backwards": 1,
}

func (x ReadReq_Options_ReadDirection) String() string {
	return proto.EnumName(ReadReq_Options_ReadDirection_name, int32(x))
}

func (ReadReq_Options_ReadDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 0}
}

type ReadReq struct {
	Options              *ReadReq_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadReq) Reset()         { *m = ReadReq{} }
func (m *ReadReq) String() string { return proto.CompactTextString(m) }
func (*ReadReq) ProtoMessage()    {}
func (*ReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0}
}

func (m *ReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq.Unmarshal(m, b)
}
func (m *ReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq.Marshal(b, m, deterministic)
}
func (m *ReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq.Merge(m, src)
}
func (m *ReadReq) XXX_Size() int {
	return xxx_messageInfo_ReadReq.Size(m)
}
func (m *ReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq proto.InternalMessageInfo

func (m *ReadReq) GetOptions() *ReadReq_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type ReadReq_Options struct {
	// Types that are valid to be assigned to StreamOptions:
	//	*ReadReq_Options_Stream
	//	*ReadReq_Options_All
	StreamOptions isReadReq_Options_StreamOptions `protobuf_oneof:"stream_options"`
	ReadDirection ReadReq_Options_ReadDirection   `protobuf:"varint,3,opt,name=read_direction,json=readDirection,proto3,enum=event_store.grpc.streams.ReadReq_Options_ReadDirection" json:"read_direction,omitempty"`
	ResolveLinks  bool                            `protobuf:"varint,4,opt,name=resolve_links,json=resolveLinks,proto3" json:"resolve_links,omitempty"`
	// Types that are valid to be assigned to CountOptions:
	//	*ReadReq_Options_Count
	//	*ReadReq_Options_Subscription
	CountOptions isReadReq_Options_CountOptions `protobuf_oneof:"count_options"`
	// Types that are valid to be assigned to FilterOptions:
	//	*ReadReq_Options_Filter
	//	*ReadReq_Options_NoFilter
	FilterOptions        isReadReq_Options_FilterOptions `protobuf_oneof:"filter_options"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ReadReq_Options) Reset()         { *m = ReadReq_Options{} }
func (m *ReadReq_Options) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options) ProtoMessage()    {}
func (*ReadReq_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0}
}

func (m *ReadReq_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options.Unmarshal(m, b)
}
func (m *ReadReq_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options.Merge(m, src)
}
func (m *ReadReq_Options) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options.Size(m)
}
func (m *ReadReq_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options proto.InternalMessageInfo

type isReadReq_Options_StreamOptions interface {
	isReadReq_Options_StreamOptions()
}

type ReadReq_Options_Stream struct {
	Stream *ReadReq_Options_StreamOptions `protobuf:"bytes,1,opt,name=stream,proto3,oneof"`
}

type ReadReq_Options_All struct {
	All *ReadReq_Options_AllOptions `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*ReadReq_Options_Stream) isReadReq_Options_StreamOptions() {}

func (*ReadReq_Options_All) isReadReq_Options_StreamOptions() {}

func (m *ReadReq_Options) GetStreamOptions() isReadReq_Options_StreamOptions {
	if m != nil {
		return m.StreamOptions
	}
	return nil
}

func (m *ReadReq_Options) GetStream() *ReadReq_Options_StreamOptions {
	if x, ok := m.GetStreamOptions().(*ReadReq_Options_Stream); ok {
		return x.Stream
	}
	return nil
}

func (m *ReadReq_Options) GetAll() *ReadReq_Options_AllOptions {
	if x, ok := m.GetStreamOptions().(*ReadReq_Options_All); ok {
		return x.All
	}
	return nil
}

func (m *ReadReq_Options) GetReadDirection() ReadReq_Options_ReadDirection {
	if m != nil {
		return m.ReadDirection
	}
	return ReadReq_Options_Forwards
}

func (m *ReadReq_Options) GetResolveLinks() bool {
	if m != nil {
		return m.ResolveLinks
	}
	return false
}

type isReadReq_Options_CountOptions interface {
	isReadReq_Options_CountOptions()
}

type ReadReq_Options_Count struct {
	Count int32 `protobuf:"varint,5,opt,name=count,proto3,oneof"`
}

type ReadReq_Options_Subscription struct {
	Subscription *ReadReq_Options_SubscriptionOptions `protobuf:"bytes,6,opt,name=subscription,proto3,oneof"`
}

func (*ReadReq_Options_Count) isReadReq_Options_CountOptions() {}

func (*ReadReq_Options_Subscription) isReadReq_Options_CountOptions() {}

func (m *ReadReq_Options) GetCountOptions() isReadReq_Options_CountOptions {
	if m != nil {
		return m.CountOptions
	}
	return nil
}

func (m *ReadReq_Options) GetCount() int32 {
	if x, ok := m.GetCountOptions().(*ReadReq_Options_Count); ok {
		return x.Count
	}
	return 0
}

func (m *ReadReq_Options) GetSubscription() *ReadReq_Options_SubscriptionOptions {
	if x, ok := m.GetCountOptions().(*ReadReq_Options_Subscription); ok {
		return x.Subscription
	}
	return nil
}

type isReadReq_Options_FilterOptions interface {
	isReadReq_Options_FilterOptions()
}

type ReadReq_Options_Filter struct {
	Filter *ReadReq_Options_FilterOptions `protobuf:"bytes,7,opt,name=filter,proto3,oneof"`
}

type ReadReq_Options_NoFilter struct {
	NoFilter *ReadReq_Empty `protobuf:"bytes,8,opt,name=no_filter,json=noFilter,proto3,oneof"`
}

func (*ReadReq_Options_Filter) isReadReq_Options_FilterOptions() {}

func (*ReadReq_Options_NoFilter) isReadReq_Options_FilterOptions() {}

func (m *ReadReq_Options) GetFilterOptions() isReadReq_Options_FilterOptions {
	if m != nil {
		return m.FilterOptions
	}
	return nil
}

func (m *ReadReq_Options) GetFilter() *ReadReq_Options_FilterOptions {
	if x, ok := m.GetFilterOptions().(*ReadReq_Options_Filter); ok {
		return x.Filter
	}
	return nil
}

func (m *ReadReq_Options) GetNoFilter() *ReadReq_Empty {
	if x, ok := m.GetFilterOptions().(*ReadReq_Options_NoFilter); ok {
		return x.NoFilter
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadReq_Options) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadReq_Options_Stream)(nil),
		(*ReadReq_Options_All)(nil),
		(*ReadReq_Options_Count)(nil),
		(*ReadReq_Options_Subscription)(nil),
		(*ReadReq_Options_Filter)(nil),
		(*ReadReq_Options_NoFilter)(nil),
	}
}

type ReadReq_Options_StreamOptions struct {
	StreamName string `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	// Types that are valid to be assigned to RevisionOptions:
	//	*ReadReq_Options_StreamOptions_Revision
	//	*ReadReq_Options_StreamOptions_Start
	//	*ReadReq_Options_StreamOptions_End
	RevisionOptions      isReadReq_Options_StreamOptions_RevisionOptions `protobuf_oneof:"revision_options"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ReadReq_Options_StreamOptions) Reset()         { *m = ReadReq_Options_StreamOptions{} }
func (m *ReadReq_Options_StreamOptions) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_StreamOptions) ProtoMessage()    {}
func (*ReadReq_Options_StreamOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 0}
}

func (m *ReadReq_Options_StreamOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_StreamOptions.Unmarshal(m, b)
}
func (m *ReadReq_Options_StreamOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_StreamOptions.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_StreamOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_StreamOptions.Merge(m, src)
}
func (m *ReadReq_Options_StreamOptions) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_StreamOptions.Size(m)
}
func (m *ReadReq_Options_StreamOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_StreamOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_StreamOptions proto.InternalMessageInfo

func (m *ReadReq_Options_StreamOptions) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type isReadReq_Options_StreamOptions_RevisionOptions interface {
	isReadReq_Options_StreamOptions_RevisionOptions()
}

type ReadReq_Options_StreamOptions_Revision struct {
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3,oneof"`
}

type ReadReq_Options_StreamOptions_Start struct {
	Start *ReadReq_Empty `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type ReadReq_Options_StreamOptions_End struct {
	End *ReadReq_Empty `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*ReadReq_Options_StreamOptions_Revision) isReadReq_Options_StreamOptions_RevisionOptions() {}

func (*ReadReq_Options_StreamOptions_Start) isReadReq_Options_StreamOptions_RevisionOptions() {}

func (*ReadReq_Options_StreamOptions_End) isReadReq_Options_StreamOptions_RevisionOptions() {}

func (m *ReadReq_Options_StreamOptions) GetRevisionOptions() isReadReq_Options_StreamOptions_RevisionOptions {
	if m != nil {
		return m.RevisionOptions
	}
	return nil
}

func (m *ReadReq_Options_StreamOptions) GetRevision() uint64 {
	if x, ok := m.GetRevisionOptions().(*ReadReq_Options_StreamOptions_Revision); ok {
		return x.Revision
	}
	return 0
}

func (m *ReadReq_Options_StreamOptions) GetStart() *ReadReq_Empty {
	if x, ok := m.GetRevisionOptions().(*ReadReq_Options_StreamOptions_Start); ok {
		return x.Start
	}
	return nil
}

func (m *ReadReq_Options_StreamOptions) GetEnd() *ReadReq_Empty {
	if x, ok := m.GetRevisionOptions().(*ReadReq_Options_StreamOptions_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadReq_Options_StreamOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadReq_Options_StreamOptions_Revision)(nil),
		(*ReadReq_Options_StreamOptions_Start)(nil),
		(*ReadReq_Options_StreamOptions_End)(nil),
	}
}

type ReadReq_Options_AllOptions struct {
	// Types that are valid to be assigned to AllOptions:
	//	*ReadReq_Options_AllOptions_Position
	//	*ReadReq_Options_AllOptions_Start
	//	*ReadReq_Options_AllOptions_End
	AllOptions           isReadReq_Options_AllOptions_AllOptions `protobuf_oneof:"all_options"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ReadReq_Options_AllOptions) Reset()         { *m = ReadReq_Options_AllOptions{} }
func (m *ReadReq_Options_AllOptions) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_AllOptions) ProtoMessage()    {}
func (*ReadReq_Options_AllOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 1}
}

func (m *ReadReq_Options_AllOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_AllOptions.Unmarshal(m, b)
}
func (m *ReadReq_Options_AllOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_AllOptions.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_AllOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_AllOptions.Merge(m, src)
}
func (m *ReadReq_Options_AllOptions) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_AllOptions.Size(m)
}
func (m *ReadReq_Options_AllOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_AllOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_AllOptions proto.InternalMessageInfo

type isReadReq_Options_AllOptions_AllOptions interface {
	isReadReq_Options_AllOptions_AllOptions()
}

type ReadReq_Options_AllOptions_Position struct {
	Position *ReadReq_Options_Position `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

type ReadReq_Options_AllOptions_Start struct {
	Start *ReadReq_Empty `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type ReadReq_Options_AllOptions_End struct {
	End *ReadReq_Empty `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*ReadReq_Options_AllOptions_Position) isReadReq_Options_AllOptions_AllOptions() {}

func (*ReadReq_Options_AllOptions_Start) isReadReq_Options_AllOptions_AllOptions() {}

func (*ReadReq_Options_AllOptions_End) isReadReq_Options_AllOptions_AllOptions() {}

func (m *ReadReq_Options_AllOptions) GetAllOptions() isReadReq_Options_AllOptions_AllOptions {
	if m != nil {
		return m.AllOptions
	}
	return nil
}

func (m *ReadReq_Options_AllOptions) GetPosition() *ReadReq_Options_Position {
	if x, ok := m.GetAllOptions().(*ReadReq_Options_AllOptions_Position); ok {
		return x.Position
	}
	return nil
}

func (m *ReadReq_Options_AllOptions) GetStart() *ReadReq_Empty {
	if x, ok := m.GetAllOptions().(*ReadReq_Options_AllOptions_Start); ok {
		return x.Start
	}
	return nil
}

func (m *ReadReq_Options_AllOptions) GetEnd() *ReadReq_Empty {
	if x, ok := m.GetAllOptions().(*ReadReq_Options_AllOptions_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadReq_Options_AllOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadReq_Options_AllOptions_Position)(nil),
		(*ReadReq_Options_AllOptions_Start)(nil),
		(*ReadReq_Options_AllOptions_End)(nil),
	}
}

type ReadReq_Options_SubscriptionOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq_Options_SubscriptionOptions) Reset()         { *m = ReadReq_Options_SubscriptionOptions{} }
func (m *ReadReq_Options_SubscriptionOptions) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_SubscriptionOptions) ProtoMessage()    {}
func (*ReadReq_Options_SubscriptionOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 2}
}

func (m *ReadReq_Options_SubscriptionOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_SubscriptionOptions.Unmarshal(m, b)
}
func (m *ReadReq_Options_SubscriptionOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_SubscriptionOptions.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_SubscriptionOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_SubscriptionOptions.Merge(m, src)
}
func (m *ReadReq_Options_SubscriptionOptions) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_SubscriptionOptions.Size(m)
}
func (m *ReadReq_Options_SubscriptionOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_SubscriptionOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_SubscriptionOptions proto.InternalMessageInfo

type ReadReq_Options_Position struct {
	CommitPosition       uint64   `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition      uint64   `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq_Options_Position) Reset()         { *m = ReadReq_Options_Position{} }
func (m *ReadReq_Options_Position) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_Position) ProtoMessage()    {}
func (*ReadReq_Options_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 3}
}

func (m *ReadReq_Options_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_Position.Unmarshal(m, b)
}
func (m *ReadReq_Options_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_Position.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_Position.Merge(m, src)
}
func (m *ReadReq_Options_Position) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_Position.Size(m)
}
func (m *ReadReq_Options_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_Position.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_Position proto.InternalMessageInfo

func (m *ReadReq_Options_Position) GetCommitPosition() uint64 {
	if m != nil {
		return m.CommitPosition
	}
	return 0
}

func (m *ReadReq_Options_Position) GetPreparePosition() uint64 {
	if m != nil {
		return m.PreparePosition
	}
	return 0
}

type ReadReq_Options_FilterOptions struct {
	// Types that are valid to be assigned to Filter:
	//	*ReadReq_Options_FilterOptions_StreamName
	//	*ReadReq_Options_FilterOptions_EventType
	Filter isReadReq_Options_FilterOptions_Filter `protobuf_oneof:"filter"`
	// Types that are valid to be assigned to Window:
	//	*ReadReq_Options_FilterOptions_Max
	//	*ReadReq_Options_FilterOptions_Count
	Window               isReadReq_Options_FilterOptions_Window `protobuf_oneof:"window"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ReadReq_Options_FilterOptions) Reset()         { *m = ReadReq_Options_FilterOptions{} }
func (m *ReadReq_Options_FilterOptions) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_FilterOptions) ProtoMessage()    {}
func (*ReadReq_Options_FilterOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 4}
}

func (m *ReadReq_Options_FilterOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_FilterOptions.Unmarshal(m, b)
}
func (m *ReadReq_Options_FilterOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_FilterOptions.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_FilterOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_FilterOptions.Merge(m, src)
}
func (m *ReadReq_Options_FilterOptions) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_FilterOptions.Size(m)
}
func (m *ReadReq_Options_FilterOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_FilterOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_FilterOptions proto.InternalMessageInfo

type isReadReq_Options_FilterOptions_Filter interface {
	isReadReq_Options_FilterOptions_Filter()
}

type ReadReq_Options_FilterOptions_StreamName struct {
	StreamName *ReadReq_Options_FilterOptions_Expression `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3,oneof"`
}

type ReadReq_Options_FilterOptions_EventType struct {
	EventType *ReadReq_Options_FilterOptions_Expression `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3,oneof"`
}

func (*ReadReq_Options_FilterOptions_StreamName) isReadReq_Options_FilterOptions_Filter() {}

func (*ReadReq_Options_FilterOptions_EventType) isReadReq_Options_FilterOptions_Filter() {}

func (m *ReadReq_Options_FilterOptions) GetFilter() isReadReq_Options_FilterOptions_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ReadReq_Options_FilterOptions) GetStreamName() *ReadReq_Options_FilterOptions_Expression {
	if x, ok := m.GetFilter().(*ReadReq_Options_FilterOptions_StreamName); ok {
		return x.StreamName
	}
	return nil
}

func (m *ReadReq_Options_FilterOptions) GetEventType() *ReadReq_Options_FilterOptions_Expression {
	if x, ok := m.GetFilter().(*ReadReq_Options_FilterOptions_EventType); ok {
		return x.EventType
	}
	return nil
}

type isReadReq_Options_FilterOptions_Window interface {
	isReadReq_Options_FilterOptions_Window()
}

type ReadReq_Options_FilterOptions_Max struct {
	Max int32 `protobuf:"varint,3,opt,name=max,proto3,oneof"`
}

type ReadReq_Options_FilterOptions_Count struct {
	Count *ReadReq_Empty `protobuf:"bytes,4,opt,name=count,proto3,oneof"`
}

func (*ReadReq_Options_FilterOptions_Max) isReadReq_Options_FilterOptions_Window() {}

func (*ReadReq_Options_FilterOptions_Count) isReadReq_Options_FilterOptions_Window() {}

func (m *ReadReq_Options_FilterOptions) GetWindow() isReadReq_Options_FilterOptions_Window {
	if m != nil {
		return m.Window
	}
	return nil
}

func (m *ReadReq_Options_FilterOptions) GetMax() int32 {
	if x, ok := m.GetWindow().(*ReadReq_Options_FilterOptions_Max); ok {
		return x.Max
	}
	return 0
}

func (m *ReadReq_Options_FilterOptions) GetCount() *ReadReq_Empty {
	if x, ok := m.GetWindow().(*ReadReq_Options_FilterOptions_Count); ok {
		return x.Count
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadReq_Options_FilterOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadReq_Options_FilterOptions_StreamName)(nil),
		(*ReadReq_Options_FilterOptions_EventType)(nil),
		(*ReadReq_Options_FilterOptions_Max)(nil),
		(*ReadReq_Options_FilterOptions_Count)(nil),
	}
}

type ReadReq_Options_FilterOptions_Expression struct {
	Regex                string   `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	Prefix               []string `protobuf:"bytes,2,rep,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq_Options_FilterOptions_Expression) Reset() {
	*m = ReadReq_Options_FilterOptions_Expression{}
}
func (m *ReadReq_Options_FilterOptions_Expression) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Options_FilterOptions_Expression) ProtoMessage()    {}
func (*ReadReq_Options_FilterOptions_Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 0, 4, 0}
}

func (m *ReadReq_Options_FilterOptions_Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Options_FilterOptions_Expression.Unmarshal(m, b)
}
func (m *ReadReq_Options_FilterOptions_Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Options_FilterOptions_Expression.Marshal(b, m, deterministic)
}
func (m *ReadReq_Options_FilterOptions_Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Options_FilterOptions_Expression.Merge(m, src)
}
func (m *ReadReq_Options_FilterOptions_Expression) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Options_FilterOptions_Expression.Size(m)
}
func (m *ReadReq_Options_FilterOptions_Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Options_FilterOptions_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Options_FilterOptions_Expression proto.InternalMessageInfo

func (m *ReadReq_Options_FilterOptions_Expression) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ReadReq_Options_FilterOptions_Expression) GetPrefix() []string {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type ReadReq_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq_Empty) Reset()         { *m = ReadReq_Empty{} }
func (m *ReadReq_Empty) String() string { return proto.CompactTextString(m) }
func (*ReadReq_Empty) ProtoMessage()    {}
func (*ReadReq_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{0, 1}
}

func (m *ReadReq_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq_Empty.Unmarshal(m, b)
}
func (m *ReadReq_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq_Empty.Marshal(b, m, deterministic)
}
func (m *ReadReq_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq_Empty.Merge(m, src)
}
func (m *ReadReq_Empty) XXX_Size() int {
	return xxx_messageInfo_ReadReq_Empty.Size(m)
}
func (m *ReadReq_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq_Empty proto.InternalMessageInfo

type ReadResp struct {
	Event                *ReadResp_ReadEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReadResp) Reset()         { *m = ReadResp{} }
func (m *ReadResp) String() string { return proto.CompactTextString(m) }
func (*ReadResp) ProtoMessage()    {}
func (*ReadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{1}
}

func (m *ReadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResp.Unmarshal(m, b)
}
func (m *ReadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResp.Marshal(b, m, deterministic)
}
func (m *ReadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResp.Merge(m, src)
}
func (m *ReadResp) XXX_Size() int {
	return xxx_messageInfo_ReadResp.Size(m)
}
func (m *ReadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResp proto.InternalMessageInfo

func (m *ReadResp) GetEvent() *ReadResp_ReadEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

type ReadResp_ReadEvent struct {
	Event *ReadResp_ReadEvent_RecordedEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Link  *ReadResp_ReadEvent_RecordedEvent `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	// Types that are valid to be assigned to Position:
	//	*ReadResp_ReadEvent_CommitPosition
	//	*ReadResp_ReadEvent_NoPosition
	Position             isReadResp_ReadEvent_Position `protobuf_oneof:"position"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ReadResp_ReadEvent) Reset()         { *m = ReadResp_ReadEvent{} }
func (m *ReadResp_ReadEvent) String() string { return proto.CompactTextString(m) }
func (*ReadResp_ReadEvent) ProtoMessage()    {}
func (*ReadResp_ReadEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{1, 0}
}

func (m *ReadResp_ReadEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResp_ReadEvent.Unmarshal(m, b)
}
func (m *ReadResp_ReadEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResp_ReadEvent.Marshal(b, m, deterministic)
}
func (m *ReadResp_ReadEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResp_ReadEvent.Merge(m, src)
}
func (m *ReadResp_ReadEvent) XXX_Size() int {
	return xxx_messageInfo_ReadResp_ReadEvent.Size(m)
}
func (m *ReadResp_ReadEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResp_ReadEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResp_ReadEvent proto.InternalMessageInfo

func (m *ReadResp_ReadEvent) GetEvent() *ReadResp_ReadEvent_RecordedEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ReadResp_ReadEvent) GetLink() *ReadResp_ReadEvent_RecordedEvent {
	if m != nil {
		return m.Link
	}
	return nil
}

type isReadResp_ReadEvent_Position interface {
	isReadResp_ReadEvent_Position()
}

type ReadResp_ReadEvent_CommitPosition struct {
	CommitPosition uint64 `protobuf:"varint,3,opt,name=commit_position,json=commitPosition,proto3,oneof"`
}

type ReadResp_ReadEvent_NoPosition struct {
	NoPosition *ReadResp_Empty `protobuf:"bytes,4,opt,name=no_position,json=noPosition,proto3,oneof"`
}

func (*ReadResp_ReadEvent_CommitPosition) isReadResp_ReadEvent_Position() {}

func (*ReadResp_ReadEvent_NoPosition) isReadResp_ReadEvent_Position() {}

func (m *ReadResp_ReadEvent) GetPosition() isReadResp_ReadEvent_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ReadResp_ReadEvent) GetCommitPosition() uint64 {
	if x, ok := m.GetPosition().(*ReadResp_ReadEvent_CommitPosition); ok {
		return x.CommitPosition
	}
	return 0
}

func (m *ReadResp_ReadEvent) GetNoPosition() *ReadResp_Empty {
	if x, ok := m.GetPosition().(*ReadResp_ReadEvent_NoPosition); ok {
		return x.NoPosition
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadResp_ReadEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadResp_ReadEvent_CommitPosition)(nil),
		(*ReadResp_ReadEvent_NoPosition)(nil),
	}
}

type ReadResp_ReadEvent_RecordedEvent struct {
	Id                   *UUID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamName           string            `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	StreamRevision       uint64            `protobuf:"varint,3,opt,name=stream_revision,json=streamRevision,proto3" json:"stream_revision,omitempty"`
	PreparePosition      uint64            `protobuf:"varint,4,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	CommitPosition       uint64            `protobuf:"varint,5,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomMetadata       []byte            `protobuf:"bytes,7,opt,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty"`
	Data                 []byte            `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReadResp_ReadEvent_RecordedEvent) Reset()         { *m = ReadResp_ReadEvent_RecordedEvent{} }
func (m *ReadResp_ReadEvent_RecordedEvent) String() string { return proto.CompactTextString(m) }
func (*ReadResp_ReadEvent_RecordedEvent) ProtoMessage()    {}
func (*ReadResp_ReadEvent_RecordedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{1, 0, 0}
}

func (m *ReadResp_ReadEvent_RecordedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent.Unmarshal(m, b)
}
func (m *ReadResp_ReadEvent_RecordedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent.Marshal(b, m, deterministic)
}
func (m *ReadResp_ReadEvent_RecordedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent.Merge(m, src)
}
func (m *ReadResp_ReadEvent_RecordedEvent) XXX_Size() int {
	return xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent.Size(m)
}
func (m *ReadResp_ReadEvent_RecordedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResp_ReadEvent_RecordedEvent proto.InternalMessageInfo

func (m *ReadResp_ReadEvent_RecordedEvent) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetStreamRevision() uint64 {
	if m != nil {
		return m.StreamRevision
	}
	return 0
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetPreparePosition() uint64 {
	if m != nil {
		return m.PreparePosition
	}
	return 0
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetCommitPosition() uint64 {
	if m != nil {
		return m.CommitPosition
	}
	return 0
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetCustomMetadata() []byte {
	if m != nil {
		return m.CustomMetadata
	}
	return nil
}

func (m *ReadResp_ReadEvent_RecordedEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReadResp_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResp_Empty) Reset()         { *m = ReadResp_Empty{} }
func (m *ReadResp_Empty) String() string { return proto.CompactTextString(m) }
func (*ReadResp_Empty) ProtoMessage()    {}
func (*ReadResp_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{1, 1}
}

func (m *ReadResp_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResp_Empty.Unmarshal(m, b)
}
func (m *ReadResp_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResp_Empty.Marshal(b, m, deterministic)
}
func (m *ReadResp_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResp_Empty.Merge(m, src)
}
func (m *ReadResp_Empty) XXX_Size() int {
	return xxx_messageInfo_ReadResp_Empty.Size(m)
}
func (m *ReadResp_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResp_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResp_Empty proto.InternalMessageInfo

type AppendReq struct {
	// Types that are valid to be assigned to Content:
	//	*AppendReq_Options_
	//	*AppendReq_ProposedMessage_
	Content              isAppendReq_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppendReq) Reset()         { *m = AppendReq{} }
func (m *AppendReq) String() string { return proto.CompactTextString(m) }
func (*AppendReq) ProtoMessage()    {}
func (*AppendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{2}
}

func (m *AppendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReq.Unmarshal(m, b)
}
func (m *AppendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReq.Marshal(b, m, deterministic)
}
func (m *AppendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReq.Merge(m, src)
}
func (m *AppendReq) XXX_Size() int {
	return xxx_messageInfo_AppendReq.Size(m)
}
func (m *AppendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReq proto.InternalMessageInfo

type isAppendReq_Content interface {
	isAppendReq_Content()
}

type AppendReq_Options_ struct {
	Options *AppendReq_Options `protobuf:"bytes,1,opt,name=options,proto3,oneof"`
}

type AppendReq_ProposedMessage_ struct {
	ProposedMessage *AppendReq_ProposedMessage `protobuf:"bytes,2,opt,name=proposed_message,json=proposedMessage,proto3,oneof"`
}

func (*AppendReq_Options_) isAppendReq_Content() {}

func (*AppendReq_ProposedMessage_) isAppendReq_Content() {}

func (m *AppendReq) GetContent() isAppendReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *AppendReq) GetOptions() *AppendReq_Options {
	if x, ok := m.GetContent().(*AppendReq_Options_); ok {
		return x.Options
	}
	return nil
}

func (m *AppendReq) GetProposedMessage() *AppendReq_ProposedMessage {
	if x, ok := m.GetContent().(*AppendReq_ProposedMessage_); ok {
		return x.ProposedMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AppendReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AppendReq_Options_)(nil),
		(*AppendReq_ProposedMessage_)(nil),
	}
}

type AppendReq_Options struct {
	StreamName string `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	// Types that are valid to be assigned to ExpectedStreamRevision:
	//	*AppendReq_Options_Revision
	//	*AppendReq_Options_NoStream
	//	*AppendReq_Options_Any
	//	*AppendReq_Options_StreamExists
	ExpectedStreamRevision isAppendReq_Options_ExpectedStreamRevision `protobuf_oneof:"expected_stream_revision"`
	XXX_NoUnkeyedLiteral   struct{}                                   `json:"-"`
	XXX_unrecognized       []byte                                     `json:"-"`
	XXX_sizecache          int32                                      `json:"-"`
}

func (m *AppendReq_Options) Reset()         { *m = AppendReq_Options{} }
func (m *AppendReq_Options) String() string { return proto.CompactTextString(m) }
func (*AppendReq_Options) ProtoMessage()    {}
func (*AppendReq_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{2, 0}
}

func (m *AppendReq_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReq_Options.Unmarshal(m, b)
}
func (m *AppendReq_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReq_Options.Marshal(b, m, deterministic)
}
func (m *AppendReq_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReq_Options.Merge(m, src)
}
func (m *AppendReq_Options) XXX_Size() int {
	return xxx_messageInfo_AppendReq_Options.Size(m)
}
func (m *AppendReq_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReq_Options.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReq_Options proto.InternalMessageInfo

func (m *AppendReq_Options) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type isAppendReq_Options_ExpectedStreamRevision interface {
	isAppendReq_Options_ExpectedStreamRevision()
}

type AppendReq_Options_Revision struct {
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3,oneof"`
}

type AppendReq_Options_NoStream struct {
	NoStream *AppendReq_Empty `protobuf:"bytes,3,opt,name=no_stream,json=noStream,proto3,oneof"`
}

type AppendReq_Options_Any struct {
	Any *AppendReq_Empty `protobuf:"bytes,4,opt,name=any,proto3,oneof"`
}

type AppendReq_Options_StreamExists struct {
	StreamExists *AppendReq_Empty `protobuf:"bytes,5,opt,name=stream_exists,json=streamExists,proto3,oneof"`
}

func (*AppendReq_Options_Revision) isAppendReq_Options_ExpectedStreamRevision() {}

func (*AppendReq_Options_NoStream) isAppendReq_Options_ExpectedStreamRevision() {}

func (*AppendReq_Options_Any) isAppendReq_Options_ExpectedStreamRevision() {}

func (*AppendReq_Options_StreamExists) isAppendReq_Options_ExpectedStreamRevision() {}

func (m *AppendReq_Options) GetExpectedStreamRevision() isAppendReq_Options_ExpectedStreamRevision {
	if m != nil {
		return m.ExpectedStreamRevision
	}
	return nil
}

func (m *AppendReq_Options) GetRevision() uint64 {
	if x, ok := m.GetExpectedStreamRevision().(*AppendReq_Options_Revision); ok {
		return x.Revision
	}
	return 0
}

func (m *AppendReq_Options) GetNoStream() *AppendReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*AppendReq_Options_NoStream); ok {
		return x.NoStream
	}
	return nil
}

func (m *AppendReq_Options) GetAny() *AppendReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*AppendReq_Options_Any); ok {
		return x.Any
	}
	return nil
}

func (m *AppendReq_Options) GetStreamExists() *AppendReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*AppendReq_Options_StreamExists); ok {
		return x.StreamExists
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AppendReq_Options) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AppendReq_Options_Revision)(nil),
		(*AppendReq_Options_NoStream)(nil),
		(*AppendReq_Options_Any)(nil),
		(*AppendReq_Options_StreamExists)(nil),
	}
}

type AppendReq_ProposedMessage struct {
	Id                   *UUID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomMetadata       []byte            `protobuf:"bytes,3,opt,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty"`
	Data                 []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppendReq_ProposedMessage) Reset()         { *m = AppendReq_ProposedMessage{} }
func (m *AppendReq_ProposedMessage) String() string { return proto.CompactTextString(m) }
func (*AppendReq_ProposedMessage) ProtoMessage()    {}
func (*AppendReq_ProposedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{2, 1}
}

func (m *AppendReq_ProposedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReq_ProposedMessage.Unmarshal(m, b)
}
func (m *AppendReq_ProposedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReq_ProposedMessage.Marshal(b, m, deterministic)
}
func (m *AppendReq_ProposedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReq_ProposedMessage.Merge(m, src)
}
func (m *AppendReq_ProposedMessage) XXX_Size() int {
	return xxx_messageInfo_AppendReq_ProposedMessage.Size(m)
}
func (m *AppendReq_ProposedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReq_ProposedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReq_ProposedMessage proto.InternalMessageInfo

func (m *AppendReq_ProposedMessage) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *AppendReq_ProposedMessage) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AppendReq_ProposedMessage) GetCustomMetadata() []byte {
	if m != nil {
		return m.CustomMetadata
	}
	return nil
}

func (m *AppendReq_ProposedMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AppendReq_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendReq_Empty) Reset()         { *m = AppendReq_Empty{} }
func (m *AppendReq_Empty) String() string { return proto.CompactTextString(m) }
func (*AppendReq_Empty) ProtoMessage()    {}
func (*AppendReq_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{2, 2}
}

func (m *AppendReq_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReq_Empty.Unmarshal(m, b)
}
func (m *AppendReq_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReq_Empty.Marshal(b, m, deterministic)
}
func (m *AppendReq_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReq_Empty.Merge(m, src)
}
func (m *AppendReq_Empty) XXX_Size() int {
	return xxx_messageInfo_AppendReq_Empty.Size(m)
}
func (m *AppendReq_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReq_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReq_Empty proto.InternalMessageInfo

type AppendResp struct {
	// Types that are valid to be assigned to CurrentRevisionOptions:
	//	*AppendResp_CurrentRevision
	//	*AppendResp_NoStream
	CurrentRevisionOptions isAppendResp_CurrentRevisionOptions `protobuf_oneof:"current_revision_options"`
	// Types that are valid to be assigned to PositionOptions:
	//	*AppendResp_Position_
	//	*AppendResp_Empty_
	PositionOptions      isAppendResp_PositionOptions `protobuf_oneof:"position_options"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AppendResp) Reset()         { *m = AppendResp{} }
func (m *AppendResp) String() string { return proto.CompactTextString(m) }
func (*AppendResp) ProtoMessage()    {}
func (*AppendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{3}
}

func (m *AppendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResp.Unmarshal(m, b)
}
func (m *AppendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResp.Marshal(b, m, deterministic)
}
func (m *AppendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResp.Merge(m, src)
}
func (m *AppendResp) XXX_Size() int {
	return xxx_messageInfo_AppendResp.Size(m)
}
func (m *AppendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResp proto.InternalMessageInfo

type isAppendResp_CurrentRevisionOptions interface {
	isAppendResp_CurrentRevisionOptions()
}

type AppendResp_CurrentRevision struct {
	CurrentRevision uint64 `protobuf:"varint,1,opt,name=current_revision,json=currentRevision,proto3,oneof"`
}

type AppendResp_NoStream struct {
	NoStream *AppendResp_Empty `protobuf:"bytes,2,opt,name=no_stream,json=noStream,proto3,oneof"`
}

func (*AppendResp_CurrentRevision) isAppendResp_CurrentRevisionOptions() {}

func (*AppendResp_NoStream) isAppendResp_CurrentRevisionOptions() {}

func (m *AppendResp) GetCurrentRevisionOptions() isAppendResp_CurrentRevisionOptions {
	if m != nil {
		return m.CurrentRevisionOptions
	}
	return nil
}

func (m *AppendResp) GetCurrentRevision() uint64 {
	if x, ok := m.GetCurrentRevisionOptions().(*AppendResp_CurrentRevision); ok {
		return x.CurrentRevision
	}
	return 0
}

func (m *AppendResp) GetNoStream() *AppendResp_Empty {
	if x, ok := m.GetCurrentRevisionOptions().(*AppendResp_NoStream); ok {
		return x.NoStream
	}
	return nil
}

type isAppendResp_PositionOptions interface {
	isAppendResp_PositionOptions()
}

type AppendResp_Position_ struct {
	Position *AppendResp_Position `protobuf:"bytes,3,opt,name=position,proto3,oneof"`
}

type AppendResp_Empty_ struct {
	Empty *AppendResp_Empty `protobuf:"bytes,4,opt,name=empty,proto3,oneof"`
}

func (*AppendResp_Position_) isAppendResp_PositionOptions() {}

func (*AppendResp_Empty_) isAppendResp_PositionOptions() {}

func (m *AppendResp) GetPositionOptions() isAppendResp_PositionOptions {
	if m != nil {
		return m.PositionOptions
	}
	return nil
}

func (m *AppendResp) GetPosition() *AppendResp_Position {
	if x, ok := m.GetPositionOptions().(*AppendResp_Position_); ok {
		return x.Position
	}
	return nil
}

func (m *AppendResp) GetEmpty() *AppendResp_Empty {
	if x, ok := m.GetPositionOptions().(*AppendResp_Empty_); ok {
		return x.Empty
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AppendResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AppendResp_CurrentRevision)(nil),
		(*AppendResp_NoStream)(nil),
		(*AppendResp_Position_)(nil),
		(*AppendResp_Empty_)(nil),
	}
}

type AppendResp_Position struct {
	CommitPosition       uint64   `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition      uint64   `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendResp_Position) Reset()         { *m = AppendResp_Position{} }
func (m *AppendResp_Position) String() string { return proto.CompactTextString(m) }
func (*AppendResp_Position) ProtoMessage()    {}
func (*AppendResp_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{3, 0}
}

func (m *AppendResp_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResp_Position.Unmarshal(m, b)
}
func (m *AppendResp_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResp_Position.Marshal(b, m, deterministic)
}
func (m *AppendResp_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResp_Position.Merge(m, src)
}
func (m *AppendResp_Position) XXX_Size() int {
	return xxx_messageInfo_AppendResp_Position.Size(m)
}
func (m *AppendResp_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResp_Position.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResp_Position proto.InternalMessageInfo

func (m *AppendResp_Position) GetCommitPosition() uint64 {
	if m != nil {
		return m.CommitPosition
	}
	return 0
}

func (m *AppendResp_Position) GetPreparePosition() uint64 {
	if m != nil {
		return m.PreparePosition
	}
	return 0
}

type AppendResp_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendResp_Empty) Reset()         { *m = AppendResp_Empty{} }
func (m *AppendResp_Empty) String() string { return proto.CompactTextString(m) }
func (*AppendResp_Empty) ProtoMessage()    {}
func (*AppendResp_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{3, 1}
}

func (m *AppendResp_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResp_Empty.Unmarshal(m, b)
}
func (m *AppendResp_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResp_Empty.Marshal(b, m, deterministic)
}
func (m *AppendResp_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResp_Empty.Merge(m, src)
}
func (m *AppendResp_Empty) XXX_Size() int {
	return xxx_messageInfo_AppendResp_Empty.Size(m)
}
func (m *AppendResp_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResp_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResp_Empty proto.InternalMessageInfo

type DeleteReq struct {
	Options              *DeleteReq_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{4}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetOptions() *DeleteReq_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type DeleteReq_Options struct {
	StreamName string `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	// Types that are valid to be assigned to ExpectedStreamRevision:
	//	*DeleteReq_Options_Revision
	//	*DeleteReq_Options_NoStream
	//	*DeleteReq_Options_Any
	//	*DeleteReq_Options_StreamExists
	ExpectedStreamRevision isDeleteReq_Options_ExpectedStreamRevision `protobuf_oneof:"expected_stream_revision"`
	XXX_NoUnkeyedLiteral   struct{}                                   `json:"-"`
	XXX_unrecognized       []byte                                     `json:"-"`
	XXX_sizecache          int32                                      `json:"-"`
}

func (m *DeleteReq_Options) Reset()         { *m = DeleteReq_Options{} }
func (m *DeleteReq_Options) String() string { return proto.CompactTextString(m) }
func (*DeleteReq_Options) ProtoMessage()    {}
func (*DeleteReq_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{4, 0}
}

func (m *DeleteReq_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq_Options.Unmarshal(m, b)
}
func (m *DeleteReq_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq_Options.Marshal(b, m, deterministic)
}
func (m *DeleteReq_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq_Options.Merge(m, src)
}
func (m *DeleteReq_Options) XXX_Size() int {
	return xxx_messageInfo_DeleteReq_Options.Size(m)
}
func (m *DeleteReq_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq_Options.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq_Options proto.InternalMessageInfo

func (m *DeleteReq_Options) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type isDeleteReq_Options_ExpectedStreamRevision interface {
	isDeleteReq_Options_ExpectedStreamRevision()
}

type DeleteReq_Options_Revision struct {
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3,oneof"`
}

type DeleteReq_Options_NoStream struct {
	NoStream *DeleteReq_Empty `protobuf:"bytes,3,opt,name=no_stream,json=noStream,proto3,oneof"`
}

type DeleteReq_Options_Any struct {
	Any *DeleteReq_Empty `protobuf:"bytes,4,opt,name=any,proto3,oneof"`
}

type DeleteReq_Options_StreamExists struct {
	StreamExists *DeleteReq_Empty `protobuf:"bytes,5,opt,name=stream_exists,json=streamExists,proto3,oneof"`
}

func (*DeleteReq_Options_Revision) isDeleteReq_Options_ExpectedStreamRevision() {}

func (*DeleteReq_Options_NoStream) isDeleteReq_Options_ExpectedStreamRevision() {}

func (*DeleteReq_Options_Any) isDeleteReq_Options_ExpectedStreamRevision() {}

func (*DeleteReq_Options_StreamExists) isDeleteReq_Options_ExpectedStreamRevision() {}

func (m *DeleteReq_Options) GetExpectedStreamRevision() isDeleteReq_Options_ExpectedStreamRevision {
	if m != nil {
		return m.ExpectedStreamRevision
	}
	return nil
}

func (m *DeleteReq_Options) GetRevision() uint64 {
	if x, ok := m.GetExpectedStreamRevision().(*DeleteReq_Options_Revision); ok {
		return x.Revision
	}
	return 0
}

func (m *DeleteReq_Options) GetNoStream() *DeleteReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*DeleteReq_Options_NoStream); ok {
		return x.NoStream
	}
	return nil
}

func (m *DeleteReq_Options) GetAny() *DeleteReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*DeleteReq_Options_Any); ok {
		return x.Any
	}
	return nil
}

func (m *DeleteReq_Options) GetStreamExists() *DeleteReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*DeleteReq_Options_StreamExists); ok {
		return x.StreamExists
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteReq_Options) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteReq_Options_Revision)(nil),
		(*DeleteReq_Options_NoStream)(nil),
		(*DeleteReq_Options_Any)(nil),
		(*DeleteReq_Options_StreamExists)(nil),
	}
}

type DeleteReq_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq_Empty) Reset()         { *m = DeleteReq_Empty{} }
func (m *DeleteReq_Empty) String() string { return proto.CompactTextString(m) }
func (*DeleteReq_Empty) ProtoMessage()    {}
func (*DeleteReq_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{4, 1}
}

func (m *DeleteReq_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq_Empty.Unmarshal(m, b)
}
func (m *DeleteReq_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq_Empty.Marshal(b, m, deterministic)
}
func (m *DeleteReq_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq_Empty.Merge(m, src)
}
func (m *DeleteReq_Empty) XXX_Size() int {
	return xxx_messageInfo_DeleteReq_Empty.Size(m)
}
func (m *DeleteReq_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq_Empty proto.InternalMessageInfo

type DeleteResp struct {
	// Types that are valid to be assigned to PositionOptions:
	//	*DeleteResp_Position_
	//	*DeleteResp_Empty_
	PositionOptions      isDeleteResp_PositionOptions `protobuf_oneof:"position_options"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{5}
}

func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (m *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(m, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

type isDeleteResp_PositionOptions interface {
	isDeleteResp_PositionOptions()
}

type DeleteResp_Position_ struct {
	Position *DeleteResp_Position `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

type DeleteResp_Empty_ struct {
	Empty *DeleteResp_Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

func (*DeleteResp_Position_) isDeleteResp_PositionOptions() {}

func (*DeleteResp_Empty_) isDeleteResp_PositionOptions() {}

func (m *DeleteResp) GetPositionOptions() isDeleteResp_PositionOptions {
	if m != nil {
		return m.PositionOptions
	}
	return nil
}

func (m *DeleteResp) GetPosition() *DeleteResp_Position {
	if x, ok := m.GetPositionOptions().(*DeleteResp_Position_); ok {
		return x.Position
	}
	return nil
}

func (m *DeleteResp) GetEmpty() *DeleteResp_Empty {
	if x, ok := m.GetPositionOptions().(*DeleteResp_Empty_); ok {
		return x.Empty
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteResp_Position_)(nil),
		(*DeleteResp_Empty_)(nil),
	}
}

type DeleteResp_Position struct {
	CommitPosition       uint64   `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition      uint64   `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp_Position) Reset()         { *m = DeleteResp_Position{} }
func (m *DeleteResp_Position) String() string { return proto.CompactTextString(m) }
func (*DeleteResp_Position) ProtoMessage()    {}
func (*DeleteResp_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{5, 0}
}

func (m *DeleteResp_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp_Position.Unmarshal(m, b)
}
func (m *DeleteResp_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp_Position.Marshal(b, m, deterministic)
}
func (m *DeleteResp_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp_Position.Merge(m, src)
}
func (m *DeleteResp_Position) XXX_Size() int {
	return xxx_messageInfo_DeleteResp_Position.Size(m)
}
func (m *DeleteResp_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp_Position.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp_Position proto.InternalMessageInfo

func (m *DeleteResp_Position) GetCommitPosition() uint64 {
	if m != nil {
		return m.CommitPosition
	}
	return 0
}

func (m *DeleteResp_Position) GetPreparePosition() uint64 {
	if m != nil {
		return m.PreparePosition
	}
	return 0
}

type DeleteResp_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp_Empty) Reset()         { *m = DeleteResp_Empty{} }
func (m *DeleteResp_Empty) String() string { return proto.CompactTextString(m) }
func (*DeleteResp_Empty) ProtoMessage()    {}
func (*DeleteResp_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{5, 1}
}

func (m *DeleteResp_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp_Empty.Unmarshal(m, b)
}
func (m *DeleteResp_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp_Empty.Marshal(b, m, deterministic)
}
func (m *DeleteResp_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp_Empty.Merge(m, src)
}
func (m *DeleteResp_Empty) XXX_Size() int {
	return xxx_messageInfo_DeleteResp_Empty.Size(m)
}
func (m *DeleteResp_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp_Empty proto.InternalMessageInfo

type TombstoneReq struct {
	Options              *TombstoneReq_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TombstoneReq) Reset()         { *m = TombstoneReq{} }
func (m *TombstoneReq) String() string { return proto.CompactTextString(m) }
func (*TombstoneReq) ProtoMessage()    {}
func (*TombstoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{6}
}

func (m *TombstoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneReq.Unmarshal(m, b)
}
func (m *TombstoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneReq.Marshal(b, m, deterministic)
}
func (m *TombstoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneReq.Merge(m, src)
}
func (m *TombstoneReq) XXX_Size() int {
	return xxx_messageInfo_TombstoneReq.Size(m)
}
func (m *TombstoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneReq proto.InternalMessageInfo

func (m *TombstoneReq) GetOptions() *TombstoneReq_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type TombstoneReq_Options struct {
	StreamName string `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	// Types that are valid to be assigned to ExpectedStreamRevision:
	//	*TombstoneReq_Options_Revision
	//	*TombstoneReq_Options_NoStream
	//	*TombstoneReq_Options_Any
	//	*TombstoneReq_Options_StreamExists
	ExpectedStreamRevision isTombstoneReq_Options_ExpectedStreamRevision `protobuf_oneof:"expected_stream_revision"`
	XXX_NoUnkeyedLiteral   struct{}                                      `json:"-"`
	XXX_unrecognized       []byte                                        `json:"-"`
	XXX_sizecache          int32                                         `json:"-"`
}

func (m *TombstoneReq_Options) Reset()         { *m = TombstoneReq_Options{} }
func (m *TombstoneReq_Options) String() string { return proto.CompactTextString(m) }
func (*TombstoneReq_Options) ProtoMessage()    {}
func (*TombstoneReq_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{6, 0}
}

func (m *TombstoneReq_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneReq_Options.Unmarshal(m, b)
}
func (m *TombstoneReq_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneReq_Options.Marshal(b, m, deterministic)
}
func (m *TombstoneReq_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneReq_Options.Merge(m, src)
}
func (m *TombstoneReq_Options) XXX_Size() int {
	return xxx_messageInfo_TombstoneReq_Options.Size(m)
}
func (m *TombstoneReq_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneReq_Options.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneReq_Options proto.InternalMessageInfo

func (m *TombstoneReq_Options) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type isTombstoneReq_Options_ExpectedStreamRevision interface {
	isTombstoneReq_Options_ExpectedStreamRevision()
}

type TombstoneReq_Options_Revision struct {
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3,oneof"`
}

type TombstoneReq_Options_NoStream struct {
	NoStream *TombstoneReq_Empty `protobuf:"bytes,3,opt,name=no_stream,json=noStream,proto3,oneof"`
}

type TombstoneReq_Options_Any struct {
	Any *TombstoneReq_Empty `protobuf:"bytes,4,opt,name=any,proto3,oneof"`
}

type TombstoneReq_Options_StreamExists struct {
	StreamExists *TombstoneReq_Empty `protobuf:"bytes,5,opt,name=stream_exists,json=streamExists,proto3,oneof"`
}

func (*TombstoneReq_Options_Revision) isTombstoneReq_Options_ExpectedStreamRevision() {}

func (*TombstoneReq_Options_NoStream) isTombstoneReq_Options_ExpectedStreamRevision() {}

func (*TombstoneReq_Options_Any) isTombstoneReq_Options_ExpectedStreamRevision() {}

func (*TombstoneReq_Options_StreamExists) isTombstoneReq_Options_ExpectedStreamRevision() {}

func (m *TombstoneReq_Options) GetExpectedStreamRevision() isTombstoneReq_Options_ExpectedStreamRevision {
	if m != nil {
		return m.ExpectedStreamRevision
	}
	return nil
}

func (m *TombstoneReq_Options) GetRevision() uint64 {
	if x, ok := m.GetExpectedStreamRevision().(*TombstoneReq_Options_Revision); ok {
		return x.Revision
	}
	return 0
}

func (m *TombstoneReq_Options) GetNoStream() *TombstoneReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*TombstoneReq_Options_NoStream); ok {
		return x.NoStream
	}
	return nil
}

func (m *TombstoneReq_Options) GetAny() *TombstoneReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*TombstoneReq_Options_Any); ok {
		return x.Any
	}
	return nil
}

func (m *TombstoneReq_Options) GetStreamExists() *TombstoneReq_Empty {
	if x, ok := m.GetExpectedStreamRevision().(*TombstoneReq_Options_StreamExists); ok {
		return x.StreamExists
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TombstoneReq_Options) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TombstoneReq_Options_Revision)(nil),
		(*TombstoneReq_Options_NoStream)(nil),
		(*TombstoneReq_Options_Any)(nil),
		(*TombstoneReq_Options_StreamExists)(nil),
	}
}

type TombstoneReq_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneReq_Empty) Reset()         { *m = TombstoneReq_Empty{} }
func (m *TombstoneReq_Empty) String() string { return proto.CompactTextString(m) }
func (*TombstoneReq_Empty) ProtoMessage()    {}
func (*TombstoneReq_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{6, 1}
}

func (m *TombstoneReq_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneReq_Empty.Unmarshal(m, b)
}
func (m *TombstoneReq_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneReq_Empty.Marshal(b, m, deterministic)
}
func (m *TombstoneReq_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneReq_Empty.Merge(m, src)
}
func (m *TombstoneReq_Empty) XXX_Size() int {
	return xxx_messageInfo_TombstoneReq_Empty.Size(m)
}
func (m *TombstoneReq_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneReq_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneReq_Empty proto.InternalMessageInfo

type TombstoneResp struct {
	// Types that are valid to be assigned to PositionOptions:
	//	*TombstoneResp_Position_
	//	*TombstoneResp_Empty_
	PositionOptions      isTombstoneResp_PositionOptions `protobuf_oneof:"position_options"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TombstoneResp) Reset()         { *m = TombstoneResp{} }
func (m *TombstoneResp) String() string { return proto.CompactTextString(m) }
func (*TombstoneResp) ProtoMessage()    {}
func (*TombstoneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{7}
}

func (m *TombstoneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneResp.Unmarshal(m, b)
}
func (m *TombstoneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneResp.Marshal(b, m, deterministic)
}
func (m *TombstoneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneResp.Merge(m, src)
}
func (m *TombstoneResp) XXX_Size() int {
	return xxx_messageInfo_TombstoneResp.Size(m)
}
func (m *TombstoneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneResp.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneResp proto.InternalMessageInfo

type isTombstoneResp_PositionOptions interface {
	isTombstoneResp_PositionOptions()
}

type TombstoneResp_Position_ struct {
	Position *TombstoneResp_Position `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

type TombstoneResp_Empty_ struct {
	Empty *TombstoneResp_Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

func (*TombstoneResp_Position_) isTombstoneResp_PositionOptions() {}

func (*TombstoneResp_Empty_) isTombstoneResp_PositionOptions() {}

func (m *TombstoneResp) GetPositionOptions() isTombstoneResp_PositionOptions {
	if m != nil {
		return m.PositionOptions
	}
	return nil
}

func (m *TombstoneResp) GetPosition() *TombstoneResp_Position {
	if x, ok := m.GetPositionOptions().(*TombstoneResp_Position_); ok {
		return x.Position
	}
	return nil
}

func (m *TombstoneResp) GetEmpty() *TombstoneResp_Empty {
	if x, ok := m.GetPositionOptions().(*TombstoneResp_Empty_); ok {
		return x.Empty
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TombstoneResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TombstoneResp_Position_)(nil),
		(*TombstoneResp_Empty_)(nil),
	}
}

type TombstoneResp_Position struct {
	CommitPosition       uint64   `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition      uint64   `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneResp_Position) Reset()         { *m = TombstoneResp_Position{} }
func (m *TombstoneResp_Position) String() string { return proto.CompactTextString(m) }
func (*TombstoneResp_Position) ProtoMessage()    {}
func (*TombstoneResp_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{7, 0}
}

func (m *TombstoneResp_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneResp_Position.Unmarshal(m, b)
}
func (m *TombstoneResp_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneResp_Position.Marshal(b, m, deterministic)
}
func (m *TombstoneResp_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneResp_Position.Merge(m, src)
}
func (m *TombstoneResp_Position) XXX_Size() int {
	return xxx_messageInfo_TombstoneResp_Position.Size(m)
}
func (m *TombstoneResp_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneResp_Position.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneResp_Position proto.InternalMessageInfo

func (m *TombstoneResp_Position) GetCommitPosition() uint64 {
	if m != nil {
		return m.CommitPosition
	}
	return 0
}

func (m *TombstoneResp_Position) GetPreparePosition() uint64 {
	if m != nil {
		return m.PreparePosition
	}
	return 0
}

type TombstoneResp_Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TombstoneResp_Empty) Reset()         { *m = TombstoneResp_Empty{} }
func (m *TombstoneResp_Empty) String() string { return proto.CompactTextString(m) }
func (*TombstoneResp_Empty) ProtoMessage()    {}
func (*TombstoneResp_Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{7, 1}
}

func (m *TombstoneResp_Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TombstoneResp_Empty.Unmarshal(m, b)
}
func (m *TombstoneResp_Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TombstoneResp_Empty.Marshal(b, m, deterministic)
}
func (m *TombstoneResp_Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TombstoneResp_Empty.Merge(m, src)
}
func (m *TombstoneResp_Empty) XXX_Size() int {
	return xxx_messageInfo_TombstoneResp_Empty.Size(m)
}
func (m *TombstoneResp_Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_TombstoneResp_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_TombstoneResp_Empty proto.InternalMessageInfo

type UUID struct {
	// Types that are valid to be assigned to Value:
	//	*UUID_Structured_
	//	*UUID_String_
	Value                isUUID_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{8}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

type isUUID_Value interface {
	isUUID_Value()
}

type UUID_Structured_ struct {
	Structured *UUID_Structured `protobuf:"bytes,1,opt,name=structured,proto3,oneof"`
}

type UUID_String_ struct {
	String_ string `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

func (*UUID_Structured_) isUUID_Value() {}

func (*UUID_String_) isUUID_Value() {}

func (m *UUID) GetValue() isUUID_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UUID) GetStructured() *UUID_Structured {
	if x, ok := m.GetValue().(*UUID_Structured_); ok {
		return x.Structured
	}
	return nil
}

func (m *UUID) GetString_() string {
	if x, ok := m.GetValue().(*UUID_String_); ok {
		return x.String_
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UUID) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UUID_Structured_)(nil),
		(*UUID_String_)(nil),
	}
}

type UUID_Structured struct {
	MostSignificantBits  int64    `protobuf:"varint,1,opt,name=most_significant_bits,json=mostSignificantBits,proto3" json:"most_significant_bits,omitempty"`
	LeastSignificantBits int64    `protobuf:"varint,2,opt,name=least_significant_bits,json=leastSignificantBits,proto3" json:"least_significant_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID_Structured) Reset()         { *m = UUID_Structured{} }
func (m *UUID_Structured) String() string { return proto.CompactTextString(m) }
func (*UUID_Structured) ProtoMessage()    {}
func (*UUID_Structured) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bbf8af0ec331d6, []int{8, 0}
}

func (m *UUID_Structured) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID_Structured.Unmarshal(m, b)
}
func (m *UUID_Structured) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID_Structured.Marshal(b, m, deterministic)
}
func (m *UUID_Structured) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID_Structured.Merge(m, src)
}
func (m *UUID_Structured) XXX_Size() int {
	return xxx_messageInfo_UUID_Structured.Size(m)
}
func (m *UUID_Structured) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID_Structured.DiscardUnknown(m)
}

var xxx_messageInfo_UUID_Structured proto.InternalMessageInfo

func (m *UUID_Structured) GetMostSignificantBits() int64 {
	if m != nil {
		return m.MostSignificantBits
	}
	return 0
}

func (m *UUID_Structured) GetLeastSignificantBits() int64 {
	if m != nil {
		return m.LeastSignificantBits
	}
	return 0
}

func init() {
	proto.RegisterEnum("event_store.grpc.streams.ReadReq_Options_ReadDirection", ReadReq_Options_ReadDirection_name, ReadReq_Options_ReadDirection_value)
	proto.RegisterType((*ReadReq)(nil), "event_store.grpc.streams.ReadReq")
	proto.RegisterType((*ReadReq_Options)(nil), "event_store.grpc.streams.ReadReq.Options")
	proto.RegisterType((*ReadReq_Options_StreamOptions)(nil), "event_store.grpc.streams.ReadReq.Options.StreamOptions")
	proto.RegisterType((*ReadReq_Options_AllOptions)(nil), "event_store.grpc.streams.ReadReq.Options.AllOptions")
	proto.RegisterType((*ReadReq_Options_SubscriptionOptions)(nil), "event_store.grpc.streams.ReadReq.Options.SubscriptionOptions")
	proto.RegisterType((*ReadReq_Options_Position)(nil), "event_store.grpc.streams.ReadReq.Options.Position")
	proto.RegisterType((*ReadReq_Options_FilterOptions)(nil), "event_store.grpc.streams.ReadReq.Options.FilterOptions")
	proto.RegisterType((*ReadReq_Options_FilterOptions_Expression)(nil), "event_store.grpc.streams.ReadReq.Options.FilterOptions.Expression")
	proto.RegisterType((*ReadReq_Empty)(nil), "event_store.grpc.streams.ReadReq.Empty")
	proto.RegisterType((*ReadResp)(nil), "event_store.grpc.streams.ReadResp")
	proto.RegisterType((*ReadResp_ReadEvent)(nil), "event_store.grpc.streams.ReadResp.ReadEvent")
	proto.RegisterType((*ReadResp_ReadEvent_RecordedEvent)(nil), "event_store.grpc.streams.ReadResp.ReadEvent.RecordedEvent")
	proto.RegisterMapType((map[string]string)(nil), "event_store.grpc.streams.ReadResp.ReadEvent.RecordedEvent.MetadataEntry")
	proto.RegisterType((*ReadResp_Empty)(nil), "event_store.grpc.streams.ReadResp.Empty")
	proto.RegisterType((*AppendReq)(nil), "event_store.grpc.streams.AppendReq")
	proto.RegisterType((*AppendReq_Options)(nil), "event_store.grpc.streams.AppendReq.Options")
	proto.RegisterType((*AppendReq_ProposedMessage)(nil), "event_store.grpc.streams.AppendReq.ProposedMessage")
	proto.RegisterMapType((map[string]string)(nil), "event_store.grpc.streams.AppendReq.ProposedMessage.MetadataEntry")
	proto.RegisterType((*AppendReq_Empty)(nil), "event_store.grpc.streams.AppendReq.Empty")
	proto.RegisterType((*AppendResp)(nil), "event_store.grpc.streams.AppendResp")
	proto.RegisterType((*AppendResp_Position)(nil), "event_store.grpc.streams.AppendResp.Position")
	proto.RegisterType((*AppendResp_Empty)(nil), "event_store.grpc.streams.AppendResp.Empty")
	proto.RegisterType((*DeleteReq)(nil), "event_store.grpc.streams.DeleteReq")
	proto.RegisterType((*DeleteReq_Options)(nil), "event_store.grpc.streams.DeleteReq.Options")
	proto.RegisterType((*DeleteReq_Empty)(nil), "event_store.grpc.streams.DeleteReq.Empty")
	proto.RegisterType((*DeleteResp)(nil), "event_store.grpc.streams.DeleteResp")
	proto.RegisterType((*DeleteResp_Position)(nil), "event_store.grpc.streams.DeleteResp.Position")
	proto.RegisterType((*DeleteResp_Empty)(nil), "event_store.grpc.streams.DeleteResp.Empty")
	proto.RegisterType((*TombstoneReq)(nil), "event_store.grpc.streams.TombstoneReq")
	proto.RegisterType((*TombstoneReq_Options)(nil), "event_store.grpc.streams.TombstoneReq.Options")
	proto.RegisterType((*TombstoneReq_Empty)(nil), "event_store.grpc.streams.TombstoneReq.Empty")
	proto.RegisterType((*TombstoneResp)(nil), "event_store.grpc.streams.TombstoneResp")
	proto.RegisterType((*TombstoneResp_Position)(nil), "event_store.grpc.streams.TombstoneResp.Position")
	proto.RegisterType((*TombstoneResp_Empty)(nil), "event_store.grpc.streams.TombstoneResp.Empty")
	proto.RegisterType((*UUID)(nil), "event_store.grpc.streams.UUID")
	proto.RegisterType((*UUID_Structured)(nil), "event_store.grpc.streams.UUID.Structured")
}

func init() { proto.RegisterFile("streams.proto", fileDescriptor_c6bbf8af0ec331d6) }

var fileDescriptor_c6bbf8af0ec331d6 = []byte{
	// 1482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5b, 0x6f, 0xdc, 0xc4,
	0x17, 0x8f, 0xed, 0xbd, 0x9e, 0xec, 0x26, 0xab, 0xe9, 0x45, 0x2b, 0xeb, 0xff, 0xa7, 0x21, 0x45,
	0x64, 0x4b, 0x5b, 0xab, 0x4a, 0x2b, 0x81, 0x5a, 0x55, 0xd0, 0xa5, 0x5b, 0xb6, 0x0a, 0x6d, 0x83,
	0xd3, 0xbe, 0x41, 0x17, 0xc7, 0x9e, 0x46, 0x56, 0x7d, 0xc3, 0x33, 0x9b, 0x26, 0x6f, 0x7c, 0x8e,
	0x4a, 0x3c, 0xf1, 0x84, 0x84, 0xf8, 0x06, 0x88, 0x57, 0xa4, 0x7e, 0x09, 0x1e, 0x78, 0x43, 0x42,
	0xea, 0x37, 0x40, 0x73, 0xf1, 0x65, 0x2f, 0xe9, 0xda, 0xdb, 0x70, 0x79, 0xf3, 0x9c, 0x99, 0xdf,
	0x6f, 0x2e, 0xe7, 0x77, 0xce, 0x9c, 0x31, 0xb4, 0x09, 0x8d, 0xb1, 0xe5, 0x13, 0x23, 0x8a, 0x43,
	0x1a, 0xa2, 0x2e, 0x3e, 0xc4, 0x01, 0x1d, 0x11, 0x1a, 0xc6, 0xd8, 0x38, 0x88, 0x23, 0xdb, 0x90,
	0xfd, 0x9b, 0xaf, 0xda, 0x50, 0x37, 0xb1, 0xe5, 0x98, 0xf8, 0x1b, 0xf4, 0x29, 0xd4, 0xc3, 0x88,
	0xba, 0x61, 0x40, 0xba, 0xca, 0x86, 0xd2, 0x5b, 0xdd, 0xbe, 0x64, 0x9c, 0x84, 0x33, 0x24, 0xc6,
	0x78, 0x24, 0x00, 0x66, 0x82, 0xd4, 0x5f, 0xb7, 0xa0, 0x2e, 0x8d, 0xe8, 0x0b, 0xa8, 0x89, 0xf1,
	0x92, 0xef, 0xc3, 0xc2, 0x7c, 0xc6, 0x1e, 0xb7, 0xcb, 0xd6, 0x70, 0xc5, 0x94, 0x44, 0x68, 0x08,
	0x9a, 0xe5, 0x79, 0x5d, 0x95, 0xf3, 0xdd, 0x28, 0xce, 0x77, 0xc7, 0xf3, 0x32, 0x32, 0x46, 0x81,
	0x9e, 0xc2, 0x5a, 0x8c, 0x2d, 0x67, 0xe4, 0xb8, 0x31, 0xb6, 0x59, 0x4f, 0x57, 0xdb, 0x50, 0x7a,
	0x6b, 0x65, 0x16, 0xc9, 0xda, 0x77, 0x13, 0xb8, 0xd9, 0x8e, 0xf3, 0x4d, 0x74, 0x11, 0xda, 0x31,
	0x26, 0xa1, 0x77, 0x88, 0x47, 0x9e, 0x1b, 0x3c, 0x27, 0xdd, 0xca, 0x86, 0xd2, 0x6b, 0x98, 0x2d,
	0x69, 0xfc, 0x9c, 0xd9, 0xd0, 0x79, 0xa8, 0xda, 0xe1, 0x38, 0xa0, 0xdd, 0xea, 0x86, 0xd2, 0xab,
	0x0e, 0x15, 0x53, 0x34, 0x91, 0x0d, 0x2d, 0x32, 0xde, 0x27, 0x76, 0xec, 0xf2, 0xa9, 0xba, 0x35,
	0xbe, 0xdf, 0xdb, 0x25, 0xce, 0x2f, 0x87, 0x4e, 0x36, 0xae, 0x98, 0x13, 0xa4, 0xcc, 0x3d, 0xcf,
	0x5c, 0x8f, 0xe2, 0xb8, 0x5b, 0x2f, 0xeb, 0x9e, 0x7b, 0x1c, 0x97, 0x10, 0xab, 0xa6, 0x24, 0x42,
	0xf7, 0xa0, 0x19, 0x84, 0x23, 0xc9, 0xda, 0xe0, 0xac, 0x5b, 0x8b, 0x59, 0x07, 0x7e, 0x44, 0x8f,
	0x87, 0xaa, 0xd9, 0x08, 0x42, 0x41, 0xac, 0xff, 0xa6, 0x40, 0x7b, 0x42, 0x02, 0xe8, 0x02, 0xac,
	0x0a, 0xd8, 0x28, 0xb0, 0x7c, 0xcc, 0x05, 0xd5, 0x34, 0x41, 0x98, 0x1e, 0x5a, 0x3e, 0x46, 0xff,
	0x83, 0x46, 0x8c, 0x0f, 0x5d, 0xc2, 0x8e, 0x8b, 0xc9, 0xa3, 0x32, 0x5c, 0x31, 0x53, 0x0b, 0xfa,
	0x18, 0xaa, 0x84, 0x5a, 0x31, 0xe5, 0x4e, 0x2e, 0xb1, 0xa8, 0x15, 0x53, 0xe0, 0xd0, 0x2d, 0xd0,
	0x70, 0xe0, 0x70, 0x27, 0x96, 0x82, 0x33, 0x54, 0x1f, 0x41, 0x27, 0x59, 0xc9, 0x28, 0x09, 0x94,
	0x3f, 0x14, 0x80, 0x4c, 0x95, 0x68, 0x17, 0x1a, 0x51, 0x48, 0x5c, 0xee, 0x6d, 0x11, 0x2d, 0xdb,
	0xc5, 0xdd, 0xb1, 0x2b, 0x91, 0x6c, 0xcb, 0x09, 0x4b, 0xb6, 0x65, 0xf5, 0xed, 0xb6, 0xac, 0x2d,
	0xb5, 0xe5, 0x36, 0xac, 0x5a, 0x9e, 0x97, 0xee, 0xf6, 0x1c, 0x9c, 0x99, 0x23, 0x49, 0xfd, 0x29,
	0x34, 0x92, 0xb5, 0xa3, 0x2d, 0x58, 0xb7, 0x43, 0xdf, 0x77, 0xe9, 0x68, 0xe2, 0x20, 0x2a, 0xe6,
	0x9a, 0x30, 0xa7, 0x03, 0x2f, 0x41, 0x27, 0x8a, 0x71, 0x64, 0xc5, 0x38, 0x1b, 0xc9, 0x3d, 0x6e,
	0xae, 0x4b, 0x7b, 0x32, 0x54, 0xff, 0x56, 0x83, 0xf6, 0x84, 0x56, 0x11, 0x9e, 0xd5, 0xd1, 0xea,
	0x76, 0x7f, 0x49, 0xe5, 0x1b, 0x83, 0xa3, 0x28, 0xc6, 0x84, 0x88, 0xa3, 0xcf, 0xab, 0xd1, 0x06,
	0x10, 0x94, 0xf4, 0x38, 0xc2, 0xd2, 0x03, 0xa7, 0x33, 0x4b, 0x93, 0x93, 0x3c, 0x3e, 0x8e, 0x30,
	0x42, 0xa0, 0xf9, 0xd6, 0x11, 0x77, 0x10, 0xcb, 0x1d, 0xac, 0xc1, 0xbc, 0x2e, 0x32, 0x4a, 0x49,
	0xa5, 0x26, 0xa9, 0x47, 0xbf, 0x09, 0x90, 0xcd, 0x87, 0xce, 0x42, 0x35, 0xc6, 0x07, 0xf8, 0x48,
	0x06, 0x9c, 0x68, 0xa0, 0xf3, 0x50, 0x8b, 0x62, 0xfc, 0xcc, 0x3d, 0xea, 0xaa, 0x1b, 0x5a, 0xaf,
	0x69, 0xca, 0x56, 0xbf, 0x91, 0x64, 0x14, 0xf6, 0xf5, 0xc2, 0x0d, 0x9c, 0xf0, 0xc5, 0xe6, 0x15,
	0x68, 0x4f, 0xe4, 0x49, 0xd4, 0x82, 0xc6, 0xbd, 0x30, 0x7e, 0x61, 0xc5, 0x0e, 0xe9, 0xac, 0xa0,
	0x36, 0x34, 0xfb, 0x96, 0xfd, 0x5c, 0x34, 0x95, 0x7e, 0x07, 0xd6, 0xa4, 0x7b, 0xa4, 0x72, 0xfa,
	0xeb, 0xd0, 0xe6, 0x0b, 0x4b, 0x0d, 0x1d, 0x58, 0x13, 0x93, 0xa4, 0xe2, 0xaa, 0x43, 0x95, 0x6f,
	0x62, 0xf3, 0x55, 0x0d, 0x1a, 0x62, 0x5b, 0x24, 0x42, 0x7d, 0xa8, 0xf2, 0xbd, 0x4b, 0x1f, 0x5f,
	0x59, 0x74, 0x12, 0x24, 0xe2, 0x1f, 0x03, 0x36, 0xca, 0x14, 0x50, 0xfd, 0x75, 0x15, 0x9a, 0xa9,
	0x11, 0xed, 0x4e, 0x32, 0xde, 0x2c, 0xc3, 0x68, 0x98, 0xd8, 0x0e, 0x63, 0x07, 0x4f, 0xf0, 0xa3,
	0x87, 0x50, 0x61, 0x97, 0x83, 0x14, 0xc8, 0xdb, 0x10, 0x72, 0x1e, 0x74, 0x69, 0x36, 0x86, 0x34,
	0x99, 0x0b, 0xa7, 0xa3, 0x68, 0x07, 0x56, 0x83, 0x30, 0x1b, 0x26, 0xe4, 0xd2, 0x2b, 0xb0, 0x82,
	0x24, 0xcc, 0x21, 0x08, 0xd3, 0x38, 0xfb, 0x59, 0x63, 0x5e, 0xce, 0xad, 0x07, 0x19, 0xa0, 0xba,
	0x8e, 0x3c, 0xa8, 0x77, 0x4e, 0x66, 0x7d, 0xf2, 0xe4, 0xfe, 0x5d, 0x53, 0x75, 0x9d, 0xe9, 0xfc,
	0xae, 0xce, 0xe4, 0xf7, 0x2d, 0x58, 0x97, 0x03, 0xd2, 0x34, 0xaf, 0x89, 0xf4, 0x20, 0xcc, 0x66,
	0x92, 0xea, 0xe7, 0xa5, 0x87, 0xca, 0xdc, 0xf4, 0x30, 0x2f, 0xe5, 0x54, 0xe7, 0xa6, 0x1c, 0x07,
	0x1a, 0x3e, 0xa6, 0x96, 0x63, 0x51, 0xab, 0x5b, 0xdb, 0xd0, 0x7a, 0xab, 0xdb, 0xc3, 0xe5, 0x7d,
	0x65, 0x3c, 0x90, 0x54, 0x83, 0x80, 0xc6, 0xc7, 0x66, 0xca, 0xcc, 0x97, 0x33, 0x26, 0x34, 0xf4,
	0x47, 0xe9, 0x64, 0xec, 0x66, 0x6e, 0x99, 0x6b, 0xc2, 0x9c, 0xe0, 0x10, 0x82, 0x0a, 0xef, 0x6d,
	0xf0, 0x5e, 0xfe, 0xad, 0xdf, 0x82, 0xf6, 0x04, 0x2f, 0xea, 0x80, 0xf6, 0x1c, 0x1f, 0xcb, 0xc0,
	0x65, 0x9f, 0x2c, 0x98, 0x0f, 0x2d, 0x6f, 0x9c, 0x9c, 0xae, 0x68, 0xdc, 0x54, 0x3f, 0x52, 0xfa,
	0x90, 0xdd, 0x3e, 0x59, 0x34, 0xfd, 0x50, 0x83, 0xe6, 0x9d, 0x28, 0xc2, 0x01, 0xaf, 0x0e, 0x3f,
	0x9b, 0xae, 0x0e, 0x2f, 0x9f, 0x7c, 0x02, 0x29, 0xca, 0xc8, 0x8a, 0xae, 0x04, 0x8d, 0xbe, 0x66,
	0xfe, 0x09, 0xa3, 0x90, 0x60, 0x67, 0xe4, 0x63, 0x42, 0xac, 0x83, 0x24, 0x41, 0x5e, 0x2f, 0xc2,
	0xb8, 0x2b, 0xb1, 0x0f, 0x04, 0x74, 0xb8, 0xc2, 0xdc, 0x3a, 0x61, 0xd2, 0x7f, 0x51, 0xb3, 0x1a,
	0xf4, 0x2d, 0xeb, 0x86, 0x21, 0x2f, 0x68, 0x64, 0x15, 0xab, 0x2d, 0xaa, 0x8a, 0xb3, 0x55, 0x26,
	0x41, 0xd2, 0x08, 0x42, 0x51, 0xc7, 0xa0, 0xdb, 0xa0, 0x59, 0xc1, 0xb1, 0x8c, 0xb3, 0x52, 0x1c,
	0x0c, 0x87, 0x76, 0x93, 0x9a, 0x7e, 0x84, 0x8f, 0x5c, 0x42, 0x09, 0x17, 0x6a, 0x49, 0xa2, 0x96,
	0xe8, 0x1a, 0x70, 0x82, 0xbe, 0x0e, 0x5d, 0x7c, 0x14, 0x61, 0x9b, 0x62, 0x67, 0x34, 0x15, 0x59,
	0xfa, 0x4b, 0x15, 0xd6, 0xa7, 0x0e, 0xba, 0x74, 0x44, 0x7f, 0x95, 0x8b, 0x19, 0x95, 0xc7, 0xcc,
	0x9d, 0x25, 0xfc, 0x5b, 0x26, 0x58, 0xb4, 0x37, 0x06, 0x4b, 0xe5, 0x94, 0x82, 0x25, 0x0d, 0x90,
	0x7e, 0x13, 0xea, 0x76, 0x18, 0x50, 0x1c, 0xd0, 0xcd, 0x9f, 0x34, 0x80, 0x64, 0x0f, 0x24, 0x42,
	0x97, 0xa1, 0x63, 0x8f, 0xe3, 0x98, 0x6d, 0x36, 0x15, 0x97, 0x22, 0xc5, 0xb5, 0x2e, 0x7b, 0xd2,
	0x84, 0x75, 0x3f, 0xaf, 0x31, 0x11, 0x09, 0x1f, 0x2c, 0x3e, 0xa9, 0x5c, 0x26, 0xce, 0x44, 0xb6,
	0x93, 0xab, 0x22, 0x85, 0x5a, 0xaf, 0x16, 0x62, 0x4a, 0x0b, 0x48, 0x25, 0x57, 0x40, 0xb2, 0x0b,
	0x94, 0xcd, 0x20, 0x35, 0x5b, 0x66, 0x4d, 0x8a, 0x29, 0xa0, 0x7f, 0x7b, 0x81, 0x97, 0xfa, 0x42,
	0x87, 0xee, 0xf4, 0x89, 0xa7, 0x15, 0x03, 0x82, 0x4e, 0xc2, 0x93, 0xd8, 0x36, 0xbf, 0xd3, 0xa0,
	0x79, 0x17, 0x7b, 0x98, 0x62, 0x96, 0xdc, 0x06, 0x25, 0x92, 0x5b, 0x8a, 0x9a, 0x7d, 0xfc, 0xfe,
	0x6b, 0x89, 0x27, 0x5b, 0xd3, 0xf2, 0x89, 0x67, 0x96, 0x63, 0xc9, 0xc4, 0x33, 0x4b, 0x54, 0x3c,
	0xf1, 0xa4, 0x97, 0xcf, 0x4b, 0x15, 0x20, 0x21, 0x22, 0xd1, 0x84, 0xb0, 0x95, 0x45, 0xc2, 0xce,
	0x70, 0xf3, 0x5f, 0x46, 0xa9, 0xb0, 0x17, 0x06, 0x5b, 0x8e, 0x29, 0x7d, 0x1c, 0xfd, 0xc3, 0xc2,
	0x9e, 0x27, 0xde, 0x1f, 0x35, 0x68, 0x3d, 0x0e, 0xfd, 0x7d, 0x42, 0xc3, 0x80, 0xeb, 0x77, 0x38,
	0xad, 0x5f, 0xe3, 0xe4, 0x3d, 0xe5, 0x81, 0xb3, 0x12, 0xfe, 0xf5, 0xf4, 0x24, 0xbc, 0x33, 0x2b,
	0xe1, 0x2b, 0x05, 0x97, 0x35, 0xab, 0xe2, 0x4f, 0xf2, 0x2a, 0x2e, 0x4b, 0xc3, 0x85, 0xbc, 0x37,
	0x5f, 0xc8, 0x65, 0xb9, 0x96, 0xd0, 0xf2, 0xf7, 0x2a, 0xb4, 0x73, 0x5c, 0x24, 0x42, 0x0f, 0x67,
	0xe4, 0x7c, 0xad, 0xd0, 0x32, 0x4e, 0x52, 0xf4, 0x60, 0x52, 0xd1, 0x57, 0x8b, 0x92, 0xfd, 0x97,
	0x44, 0xfd, 0xa7, 0x02, 0x15, 0x56, 0x3c, 0xa0, 0x1d, 0x60, 0x1a, 0x1b, 0xdb, 0x74, 0x1c, 0x63,
	0x67, 0xf1, 0xaf, 0x48, 0x86, 0x31, 0xf6, 0x52, 0x80, 0x7c, 0x88, 0xcb, 0x16, 0xea, 0xf2, 0x7f,
	0x90, 0x6e, 0x70, 0x20, 0xee, 0x71, 0xf9, 0x2b, 0xd1, 0x0d, 0x0e, 0xf4, 0x43, 0x80, 0x0c, 0x85,
	0xb6, 0xe1, 0x9c, 0x1f, 0x12, 0x3a, 0x22, 0xee, 0x41, 0xe0, 0x3e, 0x73, 0x6d, 0x2b, 0xa0, 0xa3,
	0x7d, 0x97, 0x8a, 0x78, 0xd2, 0xcc, 0x33, 0xac, 0x73, 0x2f, 0xeb, 0xeb, 0xbb, 0x94, 0xa0, 0x1b,
	0x70, 0xde, 0xc3, 0xd6, 0x3c, 0x90, 0xca, 0x41, 0x67, 0x79, 0xef, 0x14, 0xaa, 0x5f, 0x97, 0x85,
	0xc5, 0xf6, 0xef, 0x2a, 0xd4, 0x85, 0xba, 0x09, 0x7a, 0x04, 0x15, 0xf6, 0x5a, 0x40, 0xef, 0x2e,
	0x7c, 0xaf, 0xeb, 0x9b, 0x8b, 0x5f, 0x1e, 0xd7, 0x14, 0xf4, 0x04, 0x6a, 0xe2, 0x56, 0x46, 0x17,
	0x0b, 0x54, 0x5d, 0xfa, 0x7b, 0x45, 0x2e, 0xf7, 0x9e, 0x82, 0xf6, 0xa0, 0x26, 0x72, 0xe2, 0x9b,
	0x68, 0xd3, 0x0b, 0xe0, 0x4d, 0xb4, 0xb9, 0xe4, 0xfe, 0x25, 0x34, 0x53, 0x59, 0xa2, 0xf7, 0x8b,
	0xc5, 0xa3, 0xbe, 0x55, 0x50, 0xe3, 0xfd, 0x0b, 0xf0, 0x7f, 0x3b, 0xf4, 0xc5, 0x68, 0x31, 0xd8,
	0xf6, 0x5c, 0xf6, 0x0c, 0x93, 0xc3, 0xf7, 0x6b, 0xfc, 0x27, 0xf9, 0xf5, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x3b, 0x1d, 0xae, 0xfb, 0x35, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamsClient is the client API for Streams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsClient interface {
	Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (Streams_ReadClient, error)
	Append(ctx context.Context, opts ...grpc.CallOption) (Streams_AppendClient, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Tombstone(ctx context.Context, in *TombstoneReq, opts ...grpc.CallOption) (*TombstoneResp, error)
}

type streamsClient struct {
	cc *grpc.ClientConn
}

func NewStreamsClient(cc *grpc.ClientConn) StreamsClient {
	return &streamsClient{cc}
}

func (c *streamsClient) Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (Streams_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[0], "/event_store.grpc.streams.Streams/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_ReadClient interface {
	Recv() (*ReadResp, error)
	grpc.ClientStream
}

type streamsReadClient struct {
	grpc.ClientStream
}

func (x *streamsReadClient) Recv() (*ReadResp, error) {
	m := new(ReadResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) Append(ctx context.Context, opts ...grpc.CallOption) (Streams_AppendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[1], "/event_store.grpc.streams.Streams/Append", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsAppendClient{stream}
	return x, nil
}

type Streams_AppendClient interface {
	Send(*AppendReq) error
	CloseAndRecv() (*AppendResp, error)
	grpc.ClientStream
}

type streamsAppendClient struct {
	grpc.ClientStream
}

func (x *streamsAppendClient) Send(m *AppendReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamsAppendClient) CloseAndRecv() (*AppendResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AppendResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/event_store.grpc.streams.Streams/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) Tombstone(ctx context.Context, in *TombstoneReq, opts ...grpc.CallOption) (*TombstoneResp, error) {
	out := new(TombstoneResp)
	err := c.cc.Invoke(ctx, "/event_store.grpc.streams.Streams/Tombstone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamsServer is the server API for Streams service.
type StreamsServer interface {
	Read(*ReadReq, Streams_ReadServer) error
	Append(Streams_AppendServer) error
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Tombstone(context.Context, *TombstoneReq) (*TombstoneResp, error)
}

// UnimplementedStreamsServer can be embedded to have forward compatible implementations.
type UnimplementedStreamsServer struct {
}

func (*UnimplementedStreamsServer) Read(req *ReadReq, srv Streams_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedStreamsServer) Append(srv Streams_AppendServer) error {
	return status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (*UnimplementedStreamsServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedStreamsServer) Tombstone(ctx context.Context, req *TombstoneReq) (*TombstoneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tombstone not implemented")
}

func RegisterStreamsServer(s *grpc.Server, srv StreamsServer) {
	s.RegisterService(&_Streams_serviceDesc, srv)
}

func _Streams_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).Read(m, &streamsReadServer{stream})
}

type Streams_ReadServer interface {
	Send(*ReadResp) error
	grpc.ServerStream
}

type streamsReadServer struct {
	grpc.ServerStream
}

func (x *streamsReadServer) Send(m *ReadResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_Append_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamsServer).Append(&streamsAppendServer{stream})
}

type Streams_AppendServer interface {
	SendAndClose(*AppendResp) error
	Recv() (*AppendReq, error)
	grpc.ServerStream
}

type streamsAppendServer struct {
	grpc.ServerStream
}

func (x *streamsAppendServer) SendAndClose(m *AppendResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamsAppendServer) Recv() (*AppendReq, error) {
	m := new(AppendReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Streams_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_store.grpc.streams.Streams/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_Tombstone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TombstoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Tombstone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_store.grpc.streams.Streams/Tombstone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Tombstone(ctx, req.(*TombstoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Streams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event_store.grpc.streams.Streams",
	HandlerType: (*StreamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _Streams_Delete_Handler,
		},
		{
			MethodName: "Tombstone",
			Handler:    _Streams_Tombstone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _Streams_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Append",
			Handler:       _Streams_Append_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "streams.proto",
}
