package esgrpc

// StreamRevision ...
type StreamRevision int

const (
	// StreamRevisionNoStream ...
	StreamRevisionNoStream StreamRevision = iota
	// StreamRevisionAny ...
	StreamRevisionAny
	// StreamRevisionStreamExists ...
	StreamRevisionStreamExists
)
