name: CI
on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  build:
    name: Code generation & compile
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Generate protos and build project (Powershell)
      if: ${{ matrix.os == 'windows-2019' }}
      run: .\build.ps1 -generateProtos
      shell: pwsh

    - name: Generate protos and build project (Bash)
      if: ${{ matrix.os != 'windows-2019' }}
      run: ./build.sh --generate-protos

  tests:
    needs: build
    name: Tests
    strategy:
      matrix:
        domain: [ persistent, projections, operations, event_streams, user_management, connection ]
      fail-fast: false
      max-parallel: 3
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Docker Login
      run: |
        (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
        (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
        (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
        (exit 1)
        (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
        (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
        (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
        (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
        (exit 1)

    - name: Tests
      if: ${{ matrix.domain != 'connection' }}
      run: |
        touch vars.env
        docker-compose up
        cd ${{ matrix.domain }}
        go test -v ./...
        docker-compose down

    - name: Tests with cluster
      if: ${{ matrix.domain == 'connection' }}
      run: |
        touch vars.env
        docker-compose up
        docker-compose -f cluster-docker-compose.yml up -d
        cd ${{ matrix.domain }}
        go test -v ./...
        cd ..
        docker-compose -f cluster-docker-compose.yml down
        docker-compose down

  linting:
    needs: tests
    name: Linting
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Linting
      run: go vet ./...

    - name: Code formatting checks
      run: diff -u <(echo -n) <(goimports -d ./)