name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -v ./...

      - name: Tests
        run: |
          sudo apt-get install wget
          wget https://eventstore.org/downloads/ubuntu/EventStore-OSS-Linux-Ubuntu-18.04-v6.0.0-preview1.tar.gz
          tar xfv EventStore-OSS-Linux-Ubuntu-18.04-v6.0.0-preview1.tar.gz
          ./EventStore-OSS-Linux-Ubuntu-18.04-v6.0.0-preview1/eventstored --dev &
          timeout 60 bash -c 'while [[ "$(curl --insecure -u admin:changeit -s -o /dev/null -w ''%{http_code}'' https://localhost:2113/users/admin)" != "200" ]]; do sleep 5; done'
          go test ./...
